apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "koku.serviceAccountName" . }}
      containers:
        - name: koku
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DATABASE_ENGINE
              value: {{ .Values.env.DATABASE_ENGINE }}
            - name: DATABASE_NAME
              value: {{ .Values.env.DATABASE_NAME }}
            - name: DATABASE_USER
              value: {{ .Values.env.DATABASE_USER }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.env.DATABASE_PASSWORD }}
            - name: DATABASE_HOST
              value: {{ .Values.env.DATABASE_HOST }}
            - name: DATABASE_PORT
              value: {{ .Values.env.DATABASE_PORT }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}