---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
data:
  image-content-sources.yaml: |
    {{- .Values.imageContentSources | nindent 4 }}
