---
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-cluster-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    checkov.io/skip-ckv-k8s-38: CKV_K8S_38=The hypershift image requires a service account token
    checkov.io/skip-ckv-k8s-40: CKV_K8S_40=RunAsUser should not be set when using the anyuid SCC on OpenShift
    checkov.io/skip-ckv2-k8s-6: CKV2_K8S_6=NetworkPolicies should be created by namespace admins
spec:
  template:
    metadata:
      name: destroy-cluster-{{ .Release.Name }}
    spec:
      serviceAccountName: "{{ .Values.serviceAccount }}"
      restartPolicy: OnFailure
      {{- include "pod-security-context" . | nindent 6 }}
      volumes:
        {{- include "credential-volumes" . | nindent 8 }}
      initContainers:
        {{- include "aws-sts-init-container" . | nindent 8 }}
      containers:
        - name: hypershift
          image: "{{ .Values.hypershiftImage }}"
          {{- include "container-resources" . | nindent 10 }}
          {{- include "container-security-context" . | nindent 10 }}
          volumeMounts:
            - name: sts
              mountPath: /opt/hypershift/sts
          command:
            - hypershift
          args:
            - destroy
            - cluster
            - aws
            - --name
            - "{{ .Release.Name }}"
            - --infra-id
            - "{{ .Release.Name | trunc -12 }}"
            - --namespace
            - "{{ .Release.Namespace }}"
            - --sts-creds
            - /opt/hypershift/sts/token.json
            - --role-arn
            - "{{ .Values.hypershiftRoleArn }}"
            - --region
            - "{{ .Values.region }}"
            - --base-domain
            - "{{ .Values.baseDomain }}"
